version: 2.1
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.5
jobs:
  run-mabl-tests:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          environment-id: bIIfJiJ4lefJcKozgmNBPw-e
          application-id: jrMAwZAMF7Pn6cg8WUlgmQ-a
          browsers: chrome
          labels: CircleCI
          mabl-branch: master
workflows:
  test-my-app:
    jobs:
      - run-mabl-tests