version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.5

jobs:
  build-stg:
    docker:
      - image: cimg/base:stable
    steps:
     - run:
        name: "アプリのビルド"
        command: echo 'Buidling app'

  deploy-stg:
    docker:
      - image: cimg/base:stable
    steps:
     - run:
        name: "アプリのビルド"
        command: echo 'Buidling app'

  run-mabl-stg:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          browsers: chrome
          environment-id: bIIfJiJ4lefJcKozgmNBPw-e
          application-id: jrMAwZAMF7Pn6cg8WUlgmQ-a
          labels: CircleCI

workflows:
  deploy-stg-env:
    jobs:
      - build-stg
      - deploy-stg:
         requires:
          - build-stg
      - run-mabl-stg:
         requires:
          - deploy-stg