version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.5

jobs:
  run-mabl-test:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          browsers: chrome
          labels: CCI

workflows:
  run-tests:
    jobs:
      - run-mabl-test