version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.5

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
     - run:
        name: "アプリのビルド"
        command: echo 'Buidling app'

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
     - run:
        name: "アプリのビルド"
        command: echo 'Buidling app'

  run-mabl:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          browsers: chrome
          environment-id: bIIfJiJ4lefJcKozgmNBPw-e
          application-id: jrMAwZAMF7Pn6cg8WUlgmQ-a
          labels: CircleCI

workflows:
  run-tests:
    jobs:
      - run-mabl