version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - run:
          name: "Setup custom environment variables"
          command: echo '$MABL_API_KEY'

workflows:
  build:
    jobs:
      - build