version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.5

jobs:
  run-e2e-test-on-mabl:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          browsers: chrome
          environment-id: bIIfJiJ4lefJcKozgmNBPw-e
          application-id: jrMAwZAMF7Pn6cg8WUlgmQ-a
          labels: CCI

workflows:
  run-tests:
    jobs:
      - run-e2e-test-on-mabl